apiVersion: apps/v1beta1 # for versions before 1.6.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: udpserver
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: udpserver
    spec:
      containers:
      - name: bootnode
        image: emccmd/udpserver:latest
        ports:
        - containerPort: 3000
